# Airbnb Data Warehouse - ETL Pipeline

## 1. Import Libraries

In [35]:
import numpy as np
import pandas as pd
import glob
import os

## 2. Load Raw Datasets

In [87]:
files = glob.glob("data/raw/*.csv")

dfs = []

for file in files:
    df = pd.read_csv(file)

    filename = os.path.basename(file).replace(".csv","")

    city, day = filename.split("_",1)

    df["city"] = city.title()
    df["day_type"] = "weekend" if "weekend" in day else "weekday"

    dfs.append(df)

airbnb = pd.concat(dfs, ignore_index=True)

## 3. Explore Dataset

In [88]:
airbnb.head()

,Unnamed: 0,realSum,room_type,room_shared,room_private,person_capacity,host_is_superhost,multi,biz,cleanliness_rating,...,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat,city,day_type
0,0,194.033698,Private room,False,True,2.0,False,1,0,10.0,...,5.022964,2.539380,78.690379,4.166708,98.253896,6.846473,4.90569,52.41772,Amsterdam,weekday
1,1,344.245776,Private room,False,True,4.0,False,0,0,8.0,...,0.488389,0.239404,631.176378,33.421209,837.280757,58.342928,4.90005,52.37432,Amsterdam,weekday
2,2,264.101422,Private room,False,True,2.0,False,0,1,9.0,...,5.748312,3.651621,75.275877,3.985908,95.386955,6.646700,4.97512,52.36103,Amsterdam,weekday
3,3,433.529398,Private room,False,True,4.0,False,0,1,9.0,...,0.384862,0.439876,493.272534,26.119108,875.033098,60.973565,4.89417,52.37663,Amsterdam,weekday
4,4,485.552926,Private room,False,True,2.0,True,0,0,10.0,...,0.544738,0.318693,552.830324,29.272733,815.305740,56.811677,4.90051,52.37508,Amsterdam,weekday

In [89]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51707 entries, 0 to 51706
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Unnamed: 0                  51707 non-null  int64
 1   realSum                     51707 non-null  float64
 2   room_type                   51707 non-null  object
 3   room_shared                 51707 non-null  bool
 4   room_private                51707 non-null  bool
 5   person_capacity             51707 non-null  float64
 6   host_is_superhost           51707 non-null  bool
 7   multi                       51707 non-null  int64
 8   biz                         51707 non-null  int64
 9   cleanliness_rating          51707 non-null  float64
 10  guest_satisfaction_overall  51707 non-null  float64
 11  bedrooms                    51707 non-null  int64
 12  dist                        51707 non-null  float64
 13  metro_dist                  51707 non-null  float64
 14  attr_index                  51707 non-null  float64
 15  attr_index_norm             51707 non-null  float64
 16  rest_index                  51707 non-null  float64
 17  rest_index_norm             51707 non-null  float64
 18  lng                         51707 non-null  float64
 19  lat                         51707 non-null  float64
 20  city                        51707 non-null  object
 21  day_type                    51707 non-null  object
dtypes: bool(3), float64(12), int64(4), object(3)
memory usage: 7.6+ MB

In [90]:
airbnb.describe()

,Unnamed: 0,realSum,person_capacity,multi,biz,cleanliness_rating,guest_satisfaction_overall,bedrooms,dist,metro_dist,attr_index,attr_index_norm,rest_index,rest_index_norm,lng,lat
count,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.00000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000,51707.000000
mean,1620.502388,279.879591,3.161661,0.291353,0.350204,9.390624,92.628232,1.15876,3.191285,0.681540,294.204105,13.423792,626.856696,22.786177,7.426068,45.671128
std,1217.380366,327.948386,1.298545,0.454390,0.477038,0.954868,8.945531,0.62741,2.393803,0.858023,224.754123,9.807985,497.920226,17.804096,9.799725,5.249263
min,0.000000,34.779339,2.000000,0.000000,0.000000,2.000000,20.000000,0.00000,0.015045,0.002301,15.152201,0.926301,19.576924,0.592757,-9.226340,37.953000
25%,646.000000,148.752174,2.000000,0.000000,0.000000,9.000000,90.000000,1.00000,1.453142,0.248480,136.797385,6.380926,250.854114,8.751480,-0.072500,41.399510
50%,1334.000000,211.343089,3.000000,0.000000,0.000000,10.000000,95.000000,1.00000,2.613538,0.413269,234.331748,11.468305,522.052783,17.542238,4.873000,47.506690
75%,2382.000000,319.694287,4.000000,1.000000,1.000000,10.000000,99.000000,1.00000,4.263077,0.737840,385.756381,17.415082,832.628988,32.964603,13.518825,51.471885
max,5378.000000,18545.450285,6.000000,1.000000,1.000000,10.000000,100.000000,10.00000,25.284557,14.273577,4513.563486,100.000000,6696.156772,100.000000,23.786020,52.641410

## 4. Check Missing Values

In [91]:
airbnb.isna().sum()

Unnamed: 0                    0
realSum                       0
room_type                     0
room_shared                   0
room_private                  0
person_capacity               0
host_is_superhost             0
multi                         0
biz                           0
cleanliness_rating            0
guest_satisfaction_overall    0
bedrooms                      0
dist                          0
metro_dist                    0
attr_index                    0
attr_index_norm               0
rest_index                    0
rest_index_norm               0
lng                           0
lat                           0
city                          0
day_type                      0
dtype: int64

## 5. Check Duplicate Records

In [92]:
airbnb.duplicated().sum()

np.int64(0)

## 6. Remove Unnecessary Columns

In [93]:
airbnb.drop(columns=["Unnamed: 0"], inplace=True)

## 7. Data Type Validation

In [94]:
airbnb.dtypes

realSum                       float64
room_type                      object
room_shared                      bool
room_private                     bool
person_capacity               float64
host_is_superhost                bool
multi                           int64
biz                             int64
cleanliness_rating            float64
guest_satisfaction_overall    float64
bedrooms                        int64
dist                          float64
metro_dist                    float64
attr_index                    float64
attr_index_norm               float64
rest_index                    float64
rest_index_norm               float64
lng                           float64
lat                           float64
city                           object
day_type                       object
dtype: object

## 8. Convert Data Types

In [95]:
airbnb["person_capacity"] = airbnb["person_capacity"].astype(int)
airbnb["cleanliness_rating"] = airbnb["cleanliness_rating"].astype(int)

airbnb["multi"] = airbnb["multi"].astype(bool)
airbnb["biz"] = airbnb["biz"].astype(bool)
airbnb["host_is_superhost"] = airbnb["host_is_superhost"].astype(bool)

In [96]:
airbnb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51707 entries, 0 to 51706
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   realSum                     51707 non-null  float64
 1   room_type                   51707 non-null  object
 2   room_shared                 51707 non-null  bool
 3   room_private                51707 non-null  bool
 4   person_capacity             51707 non-null  int64
 5   host_is_superhost           51707 non-null  bool
 6   multi                       51707 non-null  bool
 7   biz                         51707 non-null  bool
 8   cleanliness_rating          51707 non-null  int64
 9   guest_satisfaction_overall  51707 non-null  float64
 10  bedrooms                    51707 non-null  int64
 11  dist                        51707 non-null  float64
 12  metro_dist                  51707 non-null  float64
 13  attr_index                  51707 non-null  float64
 14  attr_index_norm             51707 non-null  float64
 15  rest_index                  51707 non-null  float64
 16  rest_index_norm             51707 non-null  float64
 17  lng                         51707 non-null  float64
 18  lat                         51707 non-null  float64
 19  city                        51707 non-null  object
 20  day_type                    51707 non-null  object
dtypes: bool(5), float64(10), int64(3), object(3)
memory usage: 6.6+ MB

## 9. Save Clean Dataset

In [84]:
airbnb.to_csv("data/processed/airbnb.csv", index=False)

## 10. Simple Exploratory Analysis

In [97]:
print("Total Listings:", len(airbnb))
print("Average Price:", airbnb["realSum"].mean())
print("Average Rating:", airbnb["guest_satisfaction_overall"].mean())

Total Listings: 51707
Average Price: 279.8795910937968
Average Rating: 92.62823215425378

In [98]:
airbnb.groupby("city")["realSum"].mean().sort_values(ascending=False)

city
Amsterdam    573.112795
Paris        392.531403
London       362.469256
Barcelona    293.753706
Berlin       244.583752
Vienna       241.582484
Lisbon       238.210479
Rome         205.391950
Budapest     176.513548
Athens       151.744121
Name: realSum, dtype: float64

In [99]:
airbnb.groupby("room_type")["realSum"].mean()

room_type
Entire home/apt    324.315150
Private room       204.940233
Shared room        143.566164
Name: realSum, dtype: float64

In [100]:
airbnb.groupby("day_type")["guest_satisfaction_overall"].mean()

day_type
weekday    92.586549
weekend    92.668791
Name: guest_satisfaction_overall, dtype: float64